/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
   "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8f4d2854-1619-41bd-a8b5-df90a47c3646",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_A8aY37N7r",
    "aws_user_pools_web_client_id": "3r3k1hvqjan44juj4gos9osvsp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://scn5633ar5fllfzaa46676j4fi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-k742apztdzbj3boijpr73marha"
};


export default config;
